### ISSUE TITLE
Multiple cards to show/hide

### ISSUE THREAD

**Issue by RomRider** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#1]
Hi,

Love the idea, I was thinking about how to have local variables in the browser only lately and this seems the best way to achieve it.

It would be interesting to be be able be able to have a service call that would take a bunch of `id` and show/hide them based on the service data.
something like:
```
service: local_conditional_card.control
service_data:
  id1: true
  id2: false
```
`true` would show the card with the correspond `id`
`false` would hide a card with the corresponding `id`

My use case would be a menu (I'm using an `input_select` for now):
![menu](https://user-images.githubusercontent.com/21064206/76456960-34e91e00-63d8-11ea-95ac-745e9c768f14.gif)

It would still require a way to know which `id` is shown and which is not in the menu header, maybe by injecting some values into the `hass` object so that it can be accessed outside.
It would also require the ability to define the default visibility of a card.

Let me know what you think :)

**Comment by PiotrMachowski** [comment]
Nice idea, it shouldn't be hard to implement ;) I will check it out

**Comment by PiotrMachowski** [comment]
Implemented in v1.1.0

**Comment by RomRider** [comment]
Nice! Thanks. :clap:

Is there a way to know which card is displayed? To be able to highlight the menu header I'd need to be able to access that information from an object, probably the `hass` object?

**Comment by PiotrMachowski** [comment]
For now I didn't have to save this information, it should be possible to store it in `hass` object.
