### ISSUE TITLE
Service not found (android)

### ISSUE THREAD

**Issue by 1iverea9er** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#14]
At one point I started getting the error (below), but only in an android app and browser. It works fine in the browser on pc. Whats happen?

<img width="271" alt="image" src="https://user-images.githubusercontent.com/82063500/188267576-ca5fbe54-6993-4c2b-8fe4-c14cbfb40aae.png">

Card version 2.0.0.
HA vesion 2022.8.7

What information should I provide to solve the problem?

**Comment by PiotrMachowski** [comment]
There were breaking changes in v2.0.0, you have to adjust your config. Your PC probably works because of caching
