### ISSUE TITLE
FR: Section for visually Editing Card Content

### ISSUE THREAD

**Issue by dafunkydan** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#17]
Thanks for that Great Card, this brings a new Level to the Frontend-UI Interaction for Users!

I do have a Suggestion for an enhancement though, that will make the Card significantly more usable:
When editing a Conditional Card, all editing has to be done in Text. Worse, one can't 'design' a card in another Card, and then just copy it over. That slows down the Process of designing.

Wouldn't it be possible to just add a "Card" Section to the Editor? Some Custom Card do follow that Approach, E.g. the [Layout Card](https://github.com/thomasloven/lovelace-layout-card). 

![grafik](https://user-images.githubusercontent.com/103875104/220549880-6498cff8-9f75-4ac0-8dba-62deb19ca92d.png)

Thanks again for that great Contribution, it brings Interaction to where it needs to be!

**Comment by dafunkydan** [comment]
That'd be awesome if you have a Look again! I really see great potential in that Plugin, as one can use it as fully designable "Popup", or a more flexible Approach to "fold out entities". It already does that great, but lowering the Hurdle for Users probably could make it even become a real wide-spread Standard-Plugin :-)

Maybe having a Look at the Source of e.g. the linked Project might be helpful?
If you need some (Beta-) testing i'd be happy to assist!

**Comment by PiotrMachowski** [comment]
This feature has been added in version `v2.1.0`

**Comment by dafunkydan** [comment]
Thanks for your awesome Work! Great Card now becomes even better!
