### ISSUE TITLE
Hassio Integration does not add services

### ISSUE THREAD

**Issue by Chaosflori25** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#2]
I love your Plugin and your demo looks amazing, but when I tried to add it via HACS the services did not get added to my Hassio config. Can I add them manually? And if yes how?

**Comment by PiotrMachowski** [comment]
I am not sure what you mean, which services?
You have to add this card to resources and then just use it in the UI.

**Comment by Chaosflori25** [comment]
I got this error when I've tested your demo:
![image](https://user-images.githubusercontent.com/44469989/78351275-d19d7680-75a6-11ea-830e-d9c84b388198.png)

**Comment by PiotrMachowski** [comment]
Please share your UI config

**Comment by Chaosflori25** [comment]
`      - card:
          entities:
            - switch.av_input_tape
          title: Inputs
          type: button
        default: hide
        id: Input_t
        type: 'custom:local-conditional-card'
      - entities:
          - action_name: Toggle
            icon: 'mdi:power'
            name: Sun1
            service: local_conditional_card.toggle
            service_data:
              ids:
                - imput_t
            type: call-service
`

**Comment by PiotrMachowski** [comment]
Could you format it correctly?

**Comment by Chaosflori25** [comment]
> 

      - card:
          entities:
            - switch.av_input_tape
          title: Inputs
          type: button
        default: hide
        id: Input_t
        type: 'custom:local-conditional-card'
      - entities:
          - action_name: Toggle
            icon: 'mdi:power'
            name: Sun1
            service: local_conditional_card.toggle
            service_data:
              ids:
                - imput_t
            type: call-service

That's my current config for this test

**Comment by PiotrMachowski** [comment]
1. You have typo in ids: `imput_t` instead of `Input_t`
2. You have wrong configuration of button card. It should have parameter `entity` instead of `entities`

Corrected configuration:
```
  - card:
      entity: switch.av_input_tape
      type: button
    default: hide
    id: Input_t
    type: 'custom:local-conditional-card'
  - entities:
      - action_name: Toggle
        icon: 'mdi:power'
        name: Sun1
        service: local_conditional_card.toggle
        service_data:
          ids:
            - Input_t
        type: call-service
    type: entities

**Comment by 1iverea9er** [comment]
At one point I started getting the same error, but only in an android app and browser. It works fine in the browser on pc. Whats happen?
Card version 2.0.0.
HA vesion 2022.8.7

What information should I provide to solve the problem?
