### ISSUE TITLE
know what conditional card is active in jinja templates?

### ISSUE THREAD

**Issue by agoberg2** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#26]
I use buttons to show/hide conditional cards. Kind of like tabs. Is there a way to know, using jinja templates, what conditional card is active? So I could highlight the related button.

**Comment by PiotrMachowski** [comment]
No, it's not possible. You can create several buttons, put them inside conditional card with matching ids and just show/hide appropriate ones
