### ISSUE TITLE
Unable to add card

### ISSUE THREAD

**Issue by kvduijvenbode** [PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card#29]
Hi, 

I'm not able to add a card in the local-conditional-card. To show the issue, I have capture it on screen (see attachment).

When I click on a card, nothing happens. Do I miss something?

https://github.com/user-attachments/assets/e69a4fe6-8f53-446f-a7be-b04bd6fa491d

Kind regards,

Koos

**Comment by PiotrMachowski** [comment]
Fixed in [v2.1.1](https://github.com/PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card/releases/tag/v2.1.1)
